version: "3"

x-commons: &commons
  networks:
    - simple_stack

services:
  unity:
    <<: *commons
    build: ./docker/unitycatalog
    ports:
      - 8081:8080

networks:
  simple_stack:
    external: true