version: "3"

services:
  minio:
    image: minio/minio:latest
    networks:
      - simple_stack
    hostname: minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: steve
      MINIO_ROOT_PASSWORD: minecraft
    volumes:
      - minio_data_volume:/data

volumes:
  minio_data_volume:
    driver: local
    name: minio_data_volume
    driver_opts:
      type: none
      o: bind
      device: ./minio/data

networks:
  simple_stack:
    external: true