version: "3"

x-commons: &commons
  networks:
    - simple_stack

services:
  trino-coordinator:
    <<: *commons
    image: trinodb/trino:439
    container_name: trino-coordinator
    hostname: trino-coordinator
    networks:
      - simple_stack
    ports:
      - 8081:8080
    volumes:
      - ./trino/catalog:/etc/trino/catalog:ro
      - ./trino/coordinator/config.properties:/etc/trino/config.properties

  trino-worker:
    <<: *commons
    image: trinodb/trino:439
    networks:
      - simple_stack
    volumes:
      - ./trino/catalog:/etc/trino/catalog:ro
      - ./trino/worker/config.properties:/etc/trino/config.properties
    depends_on:
      - trino-coordinator

networks:
  simple_stack:
    external: true
